name: NationkraftTeleporters
author: Benjamin Frost
main: dk.nationkraft.teleporters.Teleporters
version: 1.0.0
api-version: 1.13
commands:
  nkt:
    description: Controls for NationkraftTeleporters
