name: Teleporters
author: Benjamin Frost
main: dk.benjamin1313.teleporters.Teleporters
version: 1.0.0
api-version: 1.13
commands:
  teleporters:
    description: Controls Teleporters
permissions:
  teleporter.*:
    description: teleporters permissions
    children:
      teleporter.useTeleporter: true
      teleporter.createTeleporter: true
      teleporter.deleteTeleporter: true
      teleporter.teleporterToolCommand: false
      
